
export const ALL_BANNER_REQUEST = "ALL_BANNER_REQUEST"
export const ALL_BANNER_SUCCESS = "ALL_BANNER_SUCCESS"
export const ALL_BANNER_FAIL = "ALL_BANNER_FAIL"

export const ALL_FEATURED_PRODUCTS_REQUEST = "ALL_FEATURED_PRODUCTS_REQUEST"
export const ALL_FEATURED_PRODUCTS_SUCCESS = "ALL_FEATURED_PRODUCTS_SUCCESS"
export const ALL_FEATURED_PRODUCTS_FAIL = "ALL_FEATURED_PRODUCTS_FAIL"

export const ALL_LATEST_PRODUCTS_REQUEST = "ALL_LATEST_PRODUCTS_REQUEST"
export const ALL_LATEST_PRODUCTS_SUCCESS = "ALL_LATEST_PRODUCTS_SUCCESS"
export const ALL_LATEST_PRODUCTS_FAIL = "ALL_LATEST_PRODUCTS_FAIL"

export const ALL_TRENDING_PRODUCTS_REQUEST = "ALL_TRENDING_PRODUCTS_REQUEST"
export const ALL_TRENDING_PRODUCTS_SUCCESS = "ALL_TRENDING_PRODUCTS_SUCCESS"
export const ALL_TRENDING_PRODUCTS_FAIL = "ALL_TRENDING_PRODUCTS_FAIL"


export const CLEAR_ERROR = "CLEAR_ERROR"