
export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST"
export const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS"
export const MY_ORDER_FAIL = "MY_ORDER_FAIL"

export const SINGLE_ORDER_REQUEST = "SINGLE_ORDER_REQUEST"
export const SINGLE_ORDER_SUCCESS = "SINGLE_ORDER_SUCCESS"
export const SINGLE_ORDER_FAIL = "SINGLE_ORDER_FAIL"

export const CLEAR_ERROR = "CLEAR_ERROR"