
export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"

export const CATEGORY_REQUEST = "CATEGORY_REQUEST"
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS"
export const CATEGORY_FAIL = "CATEGORY_FAIL"

export const COLOR_REQUEST = "COLOR_REQUEST"
export const COLOR_SUCCESS = "COLOR_SUCCESS"
export const COLOR_FAIL = "COLOR_FAIL"

export const SIZE_REQUEST = "SIZE_REQUEST"
export const SIZE_SUCCESS = "SIZE_SUCCESS"
export const SIZE_FAIL = "SIZE_FAIL"

export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL"

export const ALL_CATEGORY_SUCCESS = "ALL_CATEGORY_SUCCESS"

export const CLEAR_ERROR = "CLEAR_ERROR"